
import { title } from 'process'
import '../../app/globals.css'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
   
    <>
   
    <main>
        
    </main>
        
    
    
    </>
  
  )
}
